deployments:
- name: taxi_local_data
  entrypoint: 3_4/orchestrate.py:main_flow
  parameters: {}
  work_pool:
    name: taxi_pool
- name: taxi_s3_data
  entrypoint: 3_5/orchestrate_s3.py:main_flow_s3
  parameters: {}
  work_pool:
    name: taxi_pool

